### ISSUE TITLE
Intents

### ISSUE THREAD

**Issue by trenzin123** [Ihury/bot-discord-js-v13#5]
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (E:\bot-discord-js-v13-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:244:15)
    at async module.exports.login (E:\bot-discord-js-v13-main\node_modules\discord.js\src\client\Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}

**Comment by ghost** [comment]
You probably didn't enable the intents on the Discord developer page

**Comment by LMS5413** [comment]
PT-BR Suas intents estão desativadas. Para ativar entre no portal developers > Bot e ative 2 ultimas opção do **Privileged Gateway Intents**

EN-US Your intents are disabled. To activate enter the portal developers > Bot and activate 2 last option of **Privileged Gateway Intents**
